# Generated by Django 5.0.6 on 2024-06-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documents',
        ),
    ]
